server:
  port: 8004

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wk.pojo
  configuration:
    cache-enabled: true

spring:
  application:
    name: provider_hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_db_three?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


logging:
  level:
    com.wk.mapper: trace
  pattern:
    console: "%d %-5p [%c] - %m%n"

#eurkea注册中心
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka