server:
  port: 9002
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka


zuul:
  #忽略真实服务名称，只能用别名访问，如果需要屏蔽所有微服务真实名称可以用"*"
  ignored-services: provider_hystrix
  routes:
    wk.serviceId: provider_hystrix
    #给微服务起别名，两个名称都可以用
    wk.path: /wk_sc/**
  #prefix: /good      设置后所有微服务名称前面都需要加上前缀才能访问

